// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Structure comes from the docs/ folder tree: _category_.json per directory
  // (label, position, category-link doc) and sidebar_position/sidebar_label
  // frontmatter per doc, both generated from the original SUMMARY.md order.
  apiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
